version: '3'
services:
  web:
    build: .
    command: node_modules/.bin/gulp
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
