version: '3'
services:
  web:
    build: .
    ports:
      - 3000:80
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - 27017:27017
