version: '3'
services:
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/public/components
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
